#Install required packages
if (!"Matrix" %in% installed.packages()) install.packages("Matrix")
if (!"lpSolve" %in% installed.packages()) install.packages("lpSolve")
if (!"dplyr" %in% installed.packages()) install.packages("dplyr")
if (!"data.table" %in% installed.packages()) install.packages("data.table")
#if (!"Ryacas" %in% installed.packages()) install.packages("Ryacas")
#if (!"Ryacas0" %in% installed.packages()) install.packages("Ryacas0")
if (!"doSNOW" %in% installed.packages()) install.packages("doSNOW")
if (!"foreach" %in% installed.packages()) install.packages("foreach")
if (!"DEoptim" %in% installed.packages()) install.packages("DEoptim")
if (!"microbenchmark" %in% installed.packages()) install.packages("microbenchmark")
if (!"knitr" %in% installed.packages()) install.packages("knitr")
if (!"testthat" %in% installed.packages()) install.packages("testthat")


#Import installed packages
library(Matrix)
library(lpSolve)
library(dplyr)
library(data.table)
#library(Ryacas)
#library(Ryacas0)
library(doSNOW)
library(foreach)
library(DEoptim)
library("microbenchmark")
library(knitr)

#Import functions
source("import.R")
source("importNew.R")
source("matching.R")
source("matchingNew.R")
source("payoff.R")
source("payoffNew.R")
source("assignList.R")
source("inequalities.R")
source("inequalitiesNew.R")
source("dataArray.R")
source("dataArrayNew.R")
source("objective.R")
source("objectiveNew.R")
source("maximize.R")
source("maximizeNew.R")
source("confidence.R")
source("confidenceNew.R")
source("groupIDs.R")
